### ISSUE TITLE
promise exception/reject handling

### ISSUE THREAD

**Issue by neilmock** [lidcore/bs-callback#1]
didn't have a ton of time to dig in, but was wondering your thoughts on something like this, it is a contrived example but hopefully illustrates the call stack currently

https://gist.github.com/neilmock/8a31719bb13808e96b00254a51402bd6

should all the unhandled rejections "bubble up" into one exception by the handler?  the promise error call chain is a bit weird, so not sure the best way to approach

**Comment by toots** [comment]
Yeah that looks good to me. Unhandled rejections should indeed terminate the call chain and execute the callback immediately as `cb(exn, null)`. The `>>` piping makes sure of that. I think it should work the same way with `Promise` but I'm like you, this API is a bit opaque for me.

It is still possible, however, to raise an exception within the JS code, in which case if it's not caught and passed to a `BsCallback.fail` then it will stop the execution and won't be received by the final callback. This is why I try to surround most of the pipping with `try/catch` blocks:
```
try
  (...)
with exn -> fail exn cb
```

**Comment by neilmock** [comment]
i believe this was fixed by https://github.com/lidcore/bs-callback/commit/036d1979cd3ff89f89ebd18d3a1645a285fd1784
